/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.io.IOException;
import javax.swing.JOptionPane;
import servidor.Servidor;

/**
 *
 * @author danielbeta
 */
public class Consola extends javax.swing.JFrame {

    private Servidor servidor;
    
    /**
     * Creates new form Consola
     */
    public Consola(Servidor servidor) throws Exception {
        
        initComponents();
        this.limpiarConsola();
        this.campoTitulo.setText("Servidor " + servidor.obtenerIP());
        
        this.servidor = servidor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoConsola = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        botonEscanearRed = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servidor");

        campoTitulo.setFont(new java.awt.Font("Arimo", 1, 36)); // NOI18N
        campoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoTitulo.setText("campoTitulo");

        campoConsola.setEditable(false);
        campoConsola.setFont(new java.awt.Font("Arimo", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(campoConsola);

        jLabel2.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        jLabel2.setText("Consola:");

        botonEscanearRed.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        botonEscanearRed.setText("Escanear Red");
        botonEscanearRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEscanearRedActionPerformed(evt);
            }
        });

        botonLimpiar.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        botonLimpiar.setText("Limpiar Consola");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botonLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 418, Short.MAX_VALUE)
                        .addComponent(botonEscanearRed)))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEscanearRed)
                    .addComponent(botonLimpiar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
       this.limpiarConsola();
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonEscanearRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEscanearRedActionPerformed
       
//        JOptionPane.showMessageDialog(this, "Por favor espere, este proceso puede tardar un par de minutos.", "[ATENCION]", JOptionPane.INFORMATION_MESSAGE);
//        try {
//            this.servidor.escanearRed();
//        } catch (IOException ex) {
//            JOptionPane.showMessageDialog(this, "[ERROR] " + ex.getMessage(), "[ERROR]", JOptionPane.ERROR_MESSAGE);
//        }
//        JOptionPane.showMessageDialog(this, "¡Se ha escaneado la red!", "[ATENCION]", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botonEscanearRedActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEscanearRed;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JTextPane campoConsola;
    private javax.swing.JLabel campoTitulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    private void limpiarConsola(){
        
        this.campoConsola.setText("-> ");
    }
    
    public void mostrarMensajesServidor(String mensaje){
        
        this.campoConsola.setText(this.campoConsola.getText() + mensaje + "\n-> ");
    }
}
